name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip>=22.0,<25.0
  - pip:
    - mlflow==2.19.0
    - numpy==2.1.3
    - pandas==2.2.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.11.2
    - cloudpickle==3.1.1
    - psutil==5.9.0