name: CI Retrain Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-22.04
    outputs:
      RUN_ID: ${{ steps.get_run.outputs.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true 
          fetch-depth: 0

      - name: Setup Miniconda (Python 3.12.7)
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.12.7"
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install MLflow
        run: |
          pip install mlflow==2.19.0

      - name: Retrain model via MLflow Project
        run: |
          cd MLProject
          python modelling_tuning.py

      - name: Get MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(ls -dt MLProject/mlruns/0/*/ | head -n1 | xargs basename)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Commit MLflow artifacts
        run: |
          git add MLProject/mlruns/0/${{ steps.get_run.outputs.run_id }}
          git commit -m "✅ Add mlruns for RUN ${{ steps.get_run.outputs.run_id }}" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_build_and_push:
    needs: retrain
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code (for Dockerfile & mlruns)
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image from MLflow model
        run: |
          mlflow models build-docker \
            --model-uri "file://$(pwd)/MLProject/mlruns/0/${{ needs.retrain.outputs.RUN_ID }}/artifacts/model" \
            --name house-price-ci

      - name: Tag & push Docker image
        run: |
          docker tag house-price-ci:latest mraihanfauzii/house-price-ci:run-${{ github.run_number }}
          docker push mraihanfauzii/house-price-ci:run-${{ github.run_number }}
